version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo Installing dependencies...
      - pip install -r lambda/requirements.txt -t lambda/
  build:
    commands:
      - echo Packaging Lambda function...
      - cd lambda
      - zip -r ../lambda.zip .
      - cd ..
  post_build:
    commands:
      - echo Uploading Lambda zip to S3...
      - aws s3 cp lambda.zip s3://devops-assessment-artifacts-ddc-20250828/lambda.zip
      - echo Build completed.
artifacts:
  files:
    - lambda.zip
    - cloudformation/main.yml
    - cloudformation/lambda-deploy.yml
